# Generated by Django 2.2.5 on 2019-09-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0002_auto_20190904_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='cadena',
            field=models.CharField(max_length=10000),
        ),
    ]
