# Generated by Django 2.2.5 on 2019-09-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0004_auto_20190916_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='cadena1',
            field=models.IntegerField(default='', editable=False, max_length=1000),
        ),
    ]
