# Generated by Django 2.2.5 on 2019-09-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0005_auto_20190916_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='cadena1',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
